# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.13.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.0

    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install

    - run: pnpm build

    - name: TsNode - Timed
      run: |
        pnpm test:tsnode:timed
        rm -rf dist/
        rm -rf test-dist/

    - name: TsNode - GC Trace
      run: |
        pnpm test:tsnode:gc
        rm -rf dist/
        rm -rf test-dist/


    - name: TSC - timed (including source-maps)
      run: |
        pnpm test:tsc:timed
        rm -rf dist/
        rm -rf test-dist/

    - name: TSC - GC Trace (including source-maps)
      run: |
        pnpm test:tsc:gc
        rm -rf dist/
        rm -rf test-dist/



